In [1]:
import pandas as pd

In [2]:
matches= pd.read_csv("PremierLeague.csv")

In [3]:
matches.head()

,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,...,MarketMaxAwayTeam,MarketAvgHomeTeam,MarketAvgDraw,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints
0,1993-1994,1,14/08/1993,NaN,Arsenal,Coventry,0,3,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
1,1993-1994,1,14/08/1993,NaN,Aston Villa,QPR,4,1,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
2,1993-1994,1,14/08/1993,NaN,Chelsea,Blackburn,1,2,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3
3,1993-1994,1,14/08/1993,NaN,Liverpool,Sheffield Weds,2,0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0
4,1993-1994,1,14/08/1993,NaN,Man City,Leeds,1,1,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1

In [4]:
matches.shape

(11780, 42)

In [5]:
matches["HomeTeam"].value_counts()

HomeTeam
Arsenal             586
Tottenham           586
Everton             586
Man United          586
Liverpool           585
Chelsea             585
Newcastle           547
Aston Villa         530
West Ham            526
Man City            491
Southampton         434
Fulham              323
Blackburn           321
Leicester           321
Sunderland          304
Middlesbrough       266
Crystal Palace      264
Leeds               261
West Brom           247
Bolton              247
Wolves              190
Stoke               190
Burnley             171
Norwich             168
Wigan               152
Watford             152
Charlton            152
Coventry            150
Portsmouth          133
Birmingham          133
Bournemouth         133
Brighton            133
Derby               133
Swansea             133
Sheffield Weds      130
Wimbledon           129
Nott'm Forest       113
QPR                 108
Hull                 95
Sheffield United     94
Ipswich              73
Reading              57
Brentford            57
Huddersfield         38
Bradford             38
Cardiff              38
Luton                19
Blackpool            19
Barnsley             19
Swindon              18
Oldham               16
Name: count, dtype: int64

In [6]:
matches[matches["Season"]== "2023-2024"]

,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,...,MarketMaxAwayTeam,MarketAvgHomeTeam,MarketAvgDraw,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints
11400,2023-2024,1,11/08/2023,08:00:00 p. m.,Burnley,Man City,0,3,A,0.0,...,1.39,9.02,5.35,1.35,1.71,2.40,1.65,2.27,0,3
11401,2023-2024,1,12/08/2023,12:30:00 p. m.,Arsenal,Nott'm Forest,2,1,H,2.0,...,17.50,1.18,7.64,15.67,1.45,2.98,1.42,2.85,3,0
11402,2023-2024,1,12/08/2023,03:00:00 p. m.,Bournemouth,West Ham,1,1,D,0.0,...,2.75,2.69,3.44,2.64,1.95,2.03,1.88,1.94,1,1
11403,2023-2024,1,12/08/2023,03:00:00 p. m.,Brighton,Luton,4,1,H,1.0,...,10.50,1.33,5.52,9.61,1.65,2.45,1.61,2.34,3,0
11404,2023-2024,1,12/08/2023,03:00:00 p. m.,Everton,Fulham,0,1,A,0.0,...,3.45,2.24,3.43,3.30,2.04,1.92,1.97,1.86,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11775,2023-2024,38,19/05/2024,04:00:00 p. m.,Crystal Palace,Aston Villa,5,0,H,2.0,...,3.84,1.87,4.28,3.67,1.42,3.12,1.39,2.96,3,0
11776,2023-2024,38,19/05/2024,04:00:00 p. m.,Liverpool,Wolves,2,0,H,2.0,...,17.00,1.16,8.71,14.55,1.24,4.55,1.22,4.23,3,0
11777,2023-2024,38,19/05/2024,04:00:00 p. m.,Luton,Fulham,2,4,A,1.0,...,2.30,2.92,3.95,2.23,1.48,2.86,1.44,2.76,0,3
11778,2023-2024,38,19/05/2024,04:00:00 p. m.,Man City,West Ham,3,1,H,2.0,...,25.00,1.10,11.72,21.81,1.22,4.85,1.20,4.45,3,0
11779,2023-2024,38,19/05/2024,04:00:00 p. m.,Sheffield United,Tottenham,0,3,A,0.0,...,1.39,7.32,6.04,1.35,1.26,4.40,1.22,4.14,0,3

In [7]:
matches["MatchWeek"].value_counts()

MatchWeek
1     381
2     350
19    333
14    325
5     324
11    321
22    321
27    320
10    319
3     319
37    317
13    316
4     316
26    315
12    315
17    314
6     313
24    313
8     312
15    312
16    312
23    311
21    311
18    310
20    306
9     304
7     302
32    300
25    294
30    293
31    287
34    285
35    285
28    274
29    268
33    267
36    259
38    246
39     74
40     26
41     10
Name: count, dtype: int64

In [8]:
matches.dtypes

Season                     object
MatchWeek                   int64
Date                       object
Time                       object
HomeTeam                   object
AwayTeam                   object
FullTimeHomeTeamGoals       int64
FullTimeAwayTeamGoals       int64
FullTimeResult             object
HalfTimeHomeTeamGoals     float64
HalfTimeAwayTeamGoals     float64
HalfTimeResult             object
Referee                    object
HomeTeamShots             float64
AwayTeamShots             float64
HomeTeamShotsOnTarget     float64
AwayTeamShotsOnTarget     float64
HomeTeamCorners           float64
AwayTeamCorners           float64
HomeTeamFouls             float64
AwayTeamFouls             float64
HomeTeamYellowCards       float64
AwayTeamYellowCards       float64
HomeTeamRedCards          float64
AwayTeamRedCards          float64
B365HomeTeam              float64
B365Draw                  float64
B365AwayTeam              float64
B365Over2.5Goals          float64
B365Under2.5Goals         float64
MarketMaxHomeTeam         float64
MarketMaxDraw             float64
MarketMaxAwayTeam         float64
MarketAvgHomeTeam         float64
MarketAvgDraw             float64
MarketAvgAwayTeam         float64
MarketMaxOver2.5Goals     float64
MarketMaxUnder2.5Goals    float64
MarketAvgOver2.5Goals     float64
MarketAvgUnder2.5Goals    float64
HomeTeamPoints              int64
AwayTeamPoints              int64
dtype: object

In [9]:
matches["Date"]= pd.to_datetime(matches["Date"])

C:\Users\Niwanka.MSI\AppData\Local\Temp\ipykernel_1600\3518475557.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  matches["Date"]= pd.to_datetime(matches["Date"])

In [10]:
matches.dtypes

Season                            object
MatchWeek                          int64
Date                      datetime64[ns]
Time                              object
HomeTeam                          object
AwayTeam                          object
FullTimeHomeTeamGoals              int64
FullTimeAwayTeamGoals              int64
FullTimeResult                    object
HalfTimeHomeTeamGoals            float64
HalfTimeAwayTeamGoals            float64
HalfTimeResult                    object
Referee                           object
HomeTeamShots                    float64
AwayTeamShots                    float64
HomeTeamShotsOnTarget            float64
AwayTeamShotsOnTarget            float64
HomeTeamCorners                  float64
AwayTeamCorners                  float64
HomeTeamFouls                    float64
AwayTeamFouls                    float64
HomeTeamYellowCards              float64
AwayTeamYellowCards              float64
HomeTeamRedCards                 float64
AwayTeamRedCards                 float64
B365HomeTeam                     float64
B365Draw                         float64
B365AwayTeam                     float64
B365Over2.5Goals                 float64
B365Under2.5Goals                float64
MarketMaxHomeTeam                float64
MarketMaxDraw                    float64
MarketMaxAwayTeam                float64
MarketAvgHomeTeam                float64
MarketAvgDraw                    float64
MarketAvgAwayTeam                float64
MarketMaxOver2.5Goals            float64
MarketMaxUnder2.5Goals           float64
MarketAvgOver2.5Goals            float64
MarketAvgUnder2.5Goals           float64
HomeTeamPoints                     int64
AwayTeamPoints                     int64
dtype: object

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
matches.dropna(subset = ['HalfTimeResult', 'HalfTimeHomeTeamGoals', 'HalfTimeAwayTeamGoals'], inplace=True)

In [13]:
matches_filtered = matches[matches['Date'].dt.year >= 2000]
matches_filtered.loc[(matches.FullTimeResult == 'H'),'FTR']=0
matches_filtered.loc[(matches.FullTimeResult == 'A'),'FTR']=2
matches_filtered.loc[(matches.FullTimeResult == 'D'),'FTR']=1

C:\Users\Niwanka.MSI\AppData\Local\Temp\ipykernel_1600\1515648413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_filtered.loc[(matches.FullTimeResult == 'H'),'FTR']=0

In [14]:
matches_filtered.head()

,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,...,MarketAvgHomeTeam,MarketAvgDraw,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints,FTR
2475,1999-2000,19,2000-01-03,NaN,Derby,Watford,2,0,H,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0.0
2476,1999-2000,19,2000-01-03,NaN,Everton,Leicester,2,2,D,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1.0
2477,1999-2000,19,2000-01-03,NaN,Leeds,Aston Villa,1,2,A,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3,2.0
2478,1999-2000,19,2000-01-03,NaN,Newcastle,West Ham,2,2,D,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1.0
2479,1999-2000,19,2000-01-03,NaN,Sheffield Weds,Arsenal,1,1,D,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1.0

In [15]:
matches_filtered["HomeTeam"].value_counts()

HomeTeam
Everton             466
Tottenham           466
Chelsea             466
Man United          465
Arsenal             464
Liverpool           464
Man City            437
Newcastle           428
West Ham            409
Aston Villa         408
Fulham              323
Southampton         314
Sunderland          274
West Brom           247
Leicester           236
Crystal Palace      228
Bolton              209
Blackburn           209
Middlesbrough       199
Stoke               190
Wolves              190
Burnley             171
Wigan               152
Watford             142
Leeds               142
Charlton            133
Swansea             133
Bournemouth         133
Birmingham          133
Brighton            133
Portsmouth          133
Norwich             133
Hull                 95
Sheffield United     76
Derby                66
Reading              57
QPR                  57
Brentford            57
Ipswich              38
Cardiff              38
Huddersfield         38
Nott'm Forest        38
Bradford             29
Coventry             28
Blackpool            19
Luton                19
Sheffield Weds       11
Wimbledon             9
Name: count, dtype: int64

In [16]:
# Combine both columns to ensure consistent encoding
all_teams = pd.concat([matches_filtered['HomeTeam'], matches_filtered['AwayTeam']]).unique()

# Initialize LabelEncoder
le_team = LabelEncoder()

# Fit LabelEncoder on all unique team names
le_team.fit(all_teams)

# Transform and create new columns with encoded values
matches_filtered['HomeTeam_index'] = le_team.transform(matches_filtered['HomeTeam'])
matches_filtered['AwayTeam_index'] = le_team.transform(matches_filtered['AwayTeam'])

C:\Users\Niwanka.MSI\AppData\Local\Temp\ipykernel_1600\1059537775.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_filtered['HomeTeam_index'] = le_team.transform(matches_filtered['HomeTeam'])
C:\Users\Niwanka.MSI\AppData\Local\Temp\ipykernel_1600\1059537775.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_filtered['AwayTeam_index'] = le_team.transform(matches_filtered['AwayTeam'])

In [17]:
matches_filtered.head()

,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,...,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints,FTR,HomeTeam_index,AwayTeam_index
2475,1999-2000,19,2000-01-03,NaN,Derby,Watford,2,0,H,1.0,...,NaN,NaN,NaN,NaN,NaN,3,0,0.0,16,42
2476,1999-2000,19,2000-01-03,NaN,Everton,Leicester,2,2,D,1.0,...,NaN,NaN,NaN,NaN,NaN,1,1,1.0,17,23
2477,1999-2000,19,2000-01-03,NaN,Leeds,Aston Villa,1,2,A,0.0,...,NaN,NaN,NaN,NaN,NaN,0,3,2.0,22,1
2478,1999-2000,19,2000-01-03,NaN,Newcastle,West Ham,2,2,D,1.0,...,NaN,NaN,NaN,NaN,NaN,1,1,1.0,29,44
2479,1999-2000,19,2000-01-03,NaN,Sheffield Weds,Arsenal,1,1,D,0.0,...,NaN,NaN,NaN,NaN,NaN,1,1,1.0,36,0

In [18]:
matches_filtered.tail()

,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,...,MarketAvgAwayTeam,MarketMaxOver2.5Goals,MarketMaxUnder2.5Goals,MarketAvgOver2.5Goals,MarketAvgUnder2.5Goals,HomeTeamPoints,AwayTeamPoints,FTR,HomeTeam_index,AwayTeam_index
11775,2023-2024,38,2024-05-19,04:00:00 p. m.,Crystal Palace,Aston Villa,5,0,H,2.0,...,3.67,1.42,3.12,1.39,2.96,3,0,0.0,15,1
11776,2023-2024,38,2024-05-19,04:00:00 p. m.,Liverpool,Wolves,2,0,H,2.0,...,14.55,1.24,4.55,1.22,4.23,3,0,0.0,24,47
11777,2023-2024,38,2024-05-19,04:00:00 p. m.,Luton,Fulham,2,4,A,1.0,...,2.23,1.48,2.86,1.44,2.76,0,3,2.0,25,18
11778,2023-2024,38,2024-05-19,04:00:00 p. m.,Man City,West Ham,3,1,H,2.0,...,21.81,1.22,4.85,1.20,4.45,3,0,0.0,26,44
11779,2023-2024,38,2024-05-19,04:00:00 p. m.,Sheffield United,Tottenham,0,3,A,0.0,...,1.35,1.26,4.40,1.22,4.14,0,3,2.0,35,41

In [19]:
columns = matches_filtered.columns

print("Columns in the DataFrame:")
for col in columns:
    print(col)

Columns in the DataFrame:
Season
MatchWeek
Date
Time
HomeTeam
AwayTeam
FullTimeHomeTeamGoals
FullTimeAwayTeamGoals
FullTimeResult
HalfTimeHomeTeamGoals
HalfTimeAwayTeamGoals
HalfTimeResult
Referee
HomeTeamShots
AwayTeamShots
HomeTeamShotsOnTarget
AwayTeamShotsOnTarget
HomeTeamCorners
AwayTeamCorners
HomeTeamFouls
AwayTeamFouls
HomeTeamYellowCards
AwayTeamYellowCards
HomeTeamRedCards
AwayTeamRedCards
B365HomeTeam
B365Draw
B365AwayTeam
B365Over2.5Goals
B365Under2.5Goals
MarketMaxHomeTeam
MarketMaxDraw
MarketMaxAwayTeam
MarketAvgHomeTeam
MarketAvgDraw
MarketAvgAwayTeam
MarketMaxOver2.5Goals
MarketMaxUnder2.5Goals
MarketAvgOver2.5Goals
MarketAvgUnder2.5Goals
HomeTeamPoints
AwayTeamPoints
FTR
HomeTeam_index
AwayTeam_index

In [20]:
columns_to_drop = [
    'B365HomeTeam', 'B365Draw', 'B365AwayTeam', 'B365Over2.5Goals', 
    'B365Under2.5Goals', 'MarketMaxHomeTeam', 'MarketMaxDraw', 
    'MarketMaxAwayTeam', 'MarketAvgHomeTeam', 'MarketAvgDraw', 
    'MarketAvgAwayTeam', 'MarketMaxOver2.5Goals', 'MarketMaxUnder2.5Goals', 
    'MarketAvgOver2.5Goals', 'MarketAvgUnder2.5Goals'
]

matches_filtered.drop(columns=columns_to_drop, inplace=True)

C:\Users\Niwanka.MSI\AppData\Local\Temp\ipykernel_1600\912534035.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches_filtered.drop(columns=columns_to_drop, inplace=True)

In [21]:
('''matches_filtered.loc[(matches_filtered.FullTimeResult == 'H'),'FullTimeResult']=0
matches_filtered.loc[(matches_filtered.FullTimeResult == 'A'),'FullTimeResult']=2
matches_filtered.loc[(matches_filtered.FullTimeResult == 'D'),'FullTimeResult']=1

matches_filtered.loc[(matches_filtered.HalfTimeResult == 'H'),'HalfTimeResult']=0
matches_filtered.loc[(matches_filtered.HalfTimeResult == 'A'),'HalfTimeResult']=2
matches_filtered.loc[(matches_filtered.HalfTimeResult == 'D'),'HalfTimeResult']=1


matches_filtered['Year'] = matches_filtered['Date'].dt.year''')

"matches_filtered.loc[(matches_filtered.FullTimeResult == 'H'),'FullTimeResult']=0\nmatches_filtered.loc[(matches_filtered.FullTimeResult == 'A'),'FullTimeResult']=2\nmatches_filtered.loc[(matches_filtered.FullTimeResult == 'D'),'FullTimeResult']=1\n\nmatches_filtered.loc[(matches_filtered.HalfTimeResult == 'H'),'HalfTimeResult']=0\nmatches_filtered.loc[(matches_filtered.HalfTimeResult == 'A'),'HalfTimeResult']=2\nmatches_filtered.loc[(matches_filtered.HalfTimeResult == 'D'),'HalfTimeResult']=1\n\n\nmatches_filtered['Year'] = matches_filtered['Date'].dt.year"

In [22]:
('''valid_teams = [
    'Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', 
    'Crystal Palace', 'Everton', 'Fulham', 'Ipswich', 'Leicester', 'Liverpool', 
    'Man City', 'Man United', 'Newcastle', 'Nott\'m Forest', 'Southampton', 
    'Tottenham', 'West Ham', 'Wolves'
]
# Filter the DataFrame
matches_filtered = matches_filtered[
    matches_filtered['HomeTeam'].isin(valid_teams) &
    matches_filtered['AwayTeam'].isin(valid_teams)
]''')

"valid_teams = [\n    'Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Chelsea', \n    'Crystal Palace', 'Everton', 'Fulham', 'Ipswich', 'Leicester', 'Liverpool', \n    'Man City', 'Man United', 'Newcastle', 'Nott'm Forest', 'Southampton', \n    'Tottenham', 'West Ham', 'Wolves'\n]\n# Filter the DataFrame\nmatches_filtered = matches_filtered[\n    matches_filtered['HomeTeam'].isin(valid_teams) &\n    matches_filtered['AwayTeam'].isin(valid_teams)\n]"

In [23]:

matches_filtered.tail(20)

,Season,MatchWeek,Date,Time,HomeTeam,AwayTeam,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,...,AwayTeamFouls,HomeTeamYellowCards,AwayTeamYellowCards,HomeTeamRedCards,AwayTeamRedCards,HomeTeamPoints,AwayTeamPoints,FTR,HomeTeam_index,AwayTeam_index
11760,2023-2024,37,2024-05-11,03:00:00 p. m.,Newcastle,Brighton,1,1,D,1.0,...,16.0,3.0,4.0,0.0,0.0,1,1,1.0,29,9
11761,2023-2024,37,2024-05-11,03:00:00 p. m.,Tottenham,Burnley,2,1,H,1.0,...,14.0,3.0,5.0,0.0,0.0,3,0,0.0,41,10
11762,2023-2024,37,2024-05-11,03:00:00 p. m.,West Ham,Luton,3,1,H,0.0,...,15.0,1.0,3.0,0.0,0.0,3,0,0.0,44,25
11763,2023-2024,37,2024-05-11,03:00:00 p. m.,Wolves,Crystal Palace,1,3,A,0.0,...,12.0,3.0,2.0,0.0,1.0,0,3,2.0,47,15
11764,2023-2024,37,2024-05-11,05:30:00 p. m.,Nott'm Forest,Chelsea,2,3,A,1.0,...,8.0,2.0,3.0,0.0,0.0,0,3,2.0,31,13
11765,2023-2024,37,2024-05-12,04:30:00 p. m.,Man United,Arsenal,0,1,A,0.0,...,6.0,0.0,2.0,0.0,0.0,0,3,2.0,27,0
11766,2023-2024,37,2024-05-13,08:00:00 p. m.,Aston Villa,Liverpool,3,3,D,1.0,...,15.0,1.0,1.0,0.0,0.0,1,1,1.0,1,24
11767,2023-2024,37,2024-05-14,08:00:00 p. m.,Tottenham,Man City,0,2,A,0.0,...,11.0,3.0,3.0,0.0,0.0,0,3,2.0,41,26
11768,2023-2024,37,2024-05-15,07:45:00 p. m.,Brighton,Chelsea,1,2,A,0.0,...,14.0,2.0,2.0,0.0,1.0,0,3,2.0,9,13
11769,2023-2024,37,2024-05-15,08:00:00 p. m.,Man United,Newcastle,3,2,H,1.0,...,7.0,3.0,3.0,0.0,0.0,3,0,0.0,27,29
11770,2023-2024,38,2024-05-19,04:00:00 p. m.,Arsenal,Everton,2,1,H,1.0,...,11.0,4.0,3.0,0.0,0.0,3,0,0.0,0,17
11771,2023-2024,38,2024-05-19,04:00:00 p. m.,Brentford,Newcastle,2,4,A,0.0,...,11.0,4.0,4.0,0.0,0.0,0,3,2.0,8,29
11772,2023-2024,38,2024-05-19,04:00:00 p. m.,Brighton,Man United,0,2,A,0.0,...,9.0,1.0,3.0,0.0,0.0,0,3,2.0,9,27
11773,2023-2024,38,2024-05-19,04:00:00 p. m.,Burnley,Nott'm Forest,1,2,A,0.0,...,5.0,1.0,0.0,0.0,0.0,0,3,2.0,10,31
11774,2023-2024,38,2024-05-19,04:00:00 p. m.,Chelsea,Bournemouth,2,1,H,1.0,...,9.0,2.0,3.0,0.0,0.0,3,0,0.0,13,6
11775,2023-2024,38,2024-05-19,04:00:00 p. m.,Crystal Palace,Aston Villa,5,0,H,2.0,...,8.0,1.0,4.0,0.0,0.0,3,0,0.0,15,1
11776,2023-2024,38,2024-05-19,04:00:00 p. m.,Liverpool,Wolves,2,0,H,2.0,...,11.0,1.0,1.0,0.0,1.0,3,0,0.0,24,47
11777,2023-2024,38,2024-05-19,04:00:00 p. m.,Luton,Fulham,2,4,A,1.0,...,20.0,5.0,4.0,0.0,0.0,0,3,2.0,25,18
11778,2023-2024,38,2024-05-19,04:00:00 p. m.,Man City,West Ham,3,1,H,2.0,...,12.0,0.0,1.0,0.0,0.0,3,0,0.0,26,44
11779,2023-2024,38,2024-05-19,04:00:00 p. m.,Sheffield United,Tottenham,0,3,A,0.0,...,9.0,2.0,0.0,0.0,0.0,0,3,2.0,35,41

In [24]:
matches_filtered["HomeTeam"].value_counts()

HomeTeam
Everton             466
Tottenham           466
Chelsea             466
Man United          465
Arsenal             464
Liverpool           464
Man City            437
Newcastle           428
West Ham            409
Aston Villa         408
Fulham              323
Southampton         314
Sunderland          274
West Brom           247
Leicester           236
Crystal Palace      228
Bolton              209
Blackburn           209
Middlesbrough       199
Stoke               190
Wolves              190
Burnley             171
Wigan               152
Watford             142
Leeds               142
Charlton            133
Swansea             133
Bournemouth         133
Birmingham          133
Brighton            133
Portsmouth          133
Norwich             133
Hull                 95
Sheffield United     76
Derby                66
Reading              57
QPR                  57
Brentford            57
Ipswich              38
Cardiff              38
Huddersfield         38
Nott'm Forest        38
Bradford             29
Coventry             28
Blackpool            19
Luton                19
Sheffield Weds       11
Wimbledon             9
Name: count, dtype: int64

In [25]:
dummy_teams = pd.get_dummies(matches_filtered[['HomeTeam', 'AwayTeam']])
matches_filtered = pd.concat([matches_filtered, dummy_teams], axis=1)
matches_filtered.drop(['HomeTeam', 'AwayTeam'], axis=1, inplace=True)

In [26]:
matches_filtered['year'] = matches_filtered.Date.dt.year
matches_filtered['month'] = matches_filtered.Date.dt.month

In [27]:
matches_filtered.tail(10)

,Season,MatchWeek,Date,Time,FullTimeHomeTeamGoals,FullTimeAwayTeamGoals,FullTimeResult,HalfTimeHomeTeamGoals,HalfTimeAwayTeamGoals,HalfTimeResult,...,AwayTeam_Swansea,AwayTeam_Tottenham,AwayTeam_Watford,AwayTeam_West Brom,AwayTeam_West Ham,AwayTeam_Wigan,AwayTeam_Wimbledon,AwayTeam_Wolves,year,month
11770,2023-2024,38,2024-05-19,04:00:00 p. m.,2,1,H,1.0,1.0,D,...,False,False,False,False,False,False,False,False,2024,5
11771,2023-2024,38,2024-05-19,04:00:00 p. m.,2,4,A,0.0,3.0,A,...,False,False,False,False,False,False,False,False,2024,5
11772,2023-2024,38,2024-05-19,04:00:00 p. m.,0,2,A,0.0,0.0,D,...,False,False,False,False,False,False,False,False,2024,5
11773,2023-2024,38,2024-05-19,04:00:00 p. m.,1,2,A,0.0,2.0,A,...,False,False,False,False,False,False,False,False,2024,5
11774,2023-2024,38,2024-05-19,04:00:00 p. m.,2,1,H,1.0,0.0,H,...,False,False,False,False,False,False,False,False,2024,5
11775,2023-2024,38,2024-05-19,04:00:00 p. m.,5,0,H,2.0,0.0,H,...,False,False,False,False,False,False,False,False,2024,5
11776,2023-2024,38,2024-05-19,04:00:00 p. m.,2,0,H,2.0,0.0,H,...,False,False,False,False,False,False,False,True,2024,5
11777,2023-2024,38,2024-05-19,04:00:00 p. m.,2,4,A,1.0,2.0,A,...,False,False,False,False,False,False,False,False,2024,5
11778,2023-2024,38,2024-05-19,04:00:00 p. m.,3,1,H,2.0,1.0,H,...,False,False,False,False,True,False,False,False,2024,5
11779,2023-2024,38,2024-05-19,04:00:00 p. m.,0,3,A,0.0,1.0,A,...,False,True,False,False,False,False,False,False,2024,5

In [28]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

features = ['HalfTimeHomeTeamGoals','HalfTimeAwayTeamGoals','year','month' ]
X = pd.concat([matches_filtered[features], dummy_teams], axis=1)

y = matches_filtered['FTR']
y_oneHot = tf.keras.utils.to_categorical(y,3)

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [30]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(max_depth=35,random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=35, random_state=42)

In [31]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6239793725827245
              precision    recall  f1-score   support

         0.0       0.68      0.79      0.73      1072
         1.0       0.43      0.29      0.35       571
         2.0       0.64      0.64      0.64       684

    accuracy                           0.62      2327
   macro avg       0.58      0.57      0.57      2327
weighted avg       0.60      0.62      0.61      2327

In [32]:

def predict_result(model, HomeTeam, AwayTeam, year, month, HTHG, HTAG, val_X_columns):
    # Initialize a DataFrame with zeros
    data = {col: [0] for col in val_X_columns}
    dataframe = pd.DataFrame(data)
    
    # Set the specific input values
    if f'HomeTeam_{HomeTeam}' in dataframe.columns:
        dataframe[f'HomeTeam_{HomeTeam}'] = 1
    if f'AwayTeam_{AwayTeam}' in dataframe.columns:
        dataframe[f'AwayTeam_{AwayTeam}'] = 1
    dataframe['HalfTimeHomeTeamGoals'] = HTHG
    dataframe['HalfTimeAwayTeamGoals'] = HTAG
    dataframe['year'] = year
    dataframe['month'] = month
    
    # Predict the result
    prediction = model.predict_proba(dataframe)
    
    return prediction

# Ensure val_X_columns is defined, which should be the columns from your validation set or training set
val_X_columns = X.columns

In [35]:

print(predict_result(model, 'Man city', 'Newcastle', 2025, 5, 0, 0, val_X_columns))

[[0.42596085 0.29580439 0.27823476]]

In [1]:
print(predict_result(model, 'chelsea', 'Newcastle', 2025, 5, 0, 0, val_X_columns))

NameError: name 'predict_result' is not defined